export { Icon } from '@lucide/svelte'
export * from '@lucide/svelte'

export {
  SiGithub,
  SiSvelte,
  SiCloudflare,
  SiTypescript,
  SiJavascript,
  SiDocker,
  SiNpm,
  SiYarn,
  SiBun,
  SiPnpm,
  SiVite,
  SiReact,
  SiAngular,
  SiNextdotjs,
  SiVercel,
  SiNetlify,
  SiMongodb,
  SiPostgresql,
  SiRedis,
  SiGraphql,
  SiGit,
  SiGitlab,
  SiBitbucket,
  SiStackoverflow,
  SiReddit,
  SiYoutube,
  SiTwitch,
  SiTelegram,
  SiWhatsapp,
  SiStripe,
  SiFigma,
  SiSketch,
  SiNeovim,
  SiMacos,
  SiAndroid,
  SiLinux,
  SiUbuntu,
  SiKubuntu,
  SiAlmalinux,
  SiArchlinux,
  SiDebian,
  SiFedora,
  SiPrimevue,
} from '@icons-pack/svelte-simple-icons'

export type { SiComponentType } from '@icons-pack/svelte-simple-icons'
