import type { RouteConfig } from './types'

export const ROUTES: RouteConfig[] = [
  // (public) — prerendered, no CSR (csr=false in +layout.ts)
  // Note: devStrategy is 'ssr-with-csr' because the dev server serves these via SSR with scripts
  // even though they prerender at build time. The expectedStrategy reflects production behavior.
  {
    description: 'Homepage is prerendered static HTML',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'prerendered-no-csr',
    group: '(public)',
    path: '/',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Features page is prerendered static HTML',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'prerendered-no-csr',
    group: '(public)',
    path: '/features',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Pricing page is prerendered static HTML',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'prerendered-no-csr',
    group: '(public)',
    path: '/pricing',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'About page is prerendered static HTML',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'prerendered-no-csr',
    group: '(public)',
    path: '/about',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Privacy page is prerendered static HTML',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'prerendered-no-csr',
    group: '(public)',
    path: '/privacy',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Terms page is prerendered static HTML',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'prerendered-no-csr',
    group: '(public)',
    path: '/terms',
    requiresAuth: false,
    requiresDb: false,
  },

  // (public)/contact — SSR + CSR (cannot prerender due to form actions)
  {
    description:
      'Contact page is server-rendered with client hydration (form actions prevent prerendering)',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'ssr-with-csr',
    group: '(public)/contact',
    path: '/contact',
    requiresAuth: false,
    requiresDb: false,
  },

  // (blog) — SSR + CSR hydration with edge caching
  {
    description: 'Blog index is server-side rendered with client hydration',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'ssr-with-csr',
    group: '(blog)',
    path: '/blog',
    requiresAuth: false,
    requiresDb: true,
  },

  // (auth) — default SSR + CSR hydration
  {
    description: 'Login page is server-side rendered with client hydration',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'ssr-with-csr',
    group: '(auth)',
    path: '/login',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Register page is server-side rendered with client hydration',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'ssr-with-csr',
    group: '(auth)',
    path: '/register',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Forgot password page is server-side rendered with client hydration',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'ssr-with-csr',
    group: '(auth)',
    path: '/forgot-password',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Reset password page is server-side rendered with client hydration',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'ssr-with-csr',
    group: '(auth)',
    path: '/reset-password',
    requiresAuth: false,
    requiresDb: false,
  },
  {
    description: 'Verify email page is server-side rendered with client hydration',
    devStrategy: 'ssr-with-csr',
    expectedStrategy: 'ssr-with-csr',
    group: '(auth)',
    path: '/verify-email',
    requiresAuth: false,
    requiresDb: false,
  },

  // (app) — CSR-only SPA, redirects to login when unauthenticated
  {
    authenticatedStrategy: 'csr-only',
    description: '/app redirects to /app/dashboard',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(app)',
    path: '/app',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'App dashboard redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(app)',
    path: '/app/dashboard',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'App items redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(app)',
    path: '/app/items',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'App profile redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(app)',
    path: '/app/profile',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'App settings redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(app)',
    path: '/app/settings',
    requiresAuth: true,
    requiresDb: false,
  },

  // (admin) — CSR-only SPA, redirects to login when unauthenticated
  {
    authenticatedStrategy: 'csr-only',
    description: '/admin redirects to /admin/dashboard',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(admin)',
    path: '/admin',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'Admin dashboard redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(admin)',
    path: '/admin/dashboard',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'Admin users redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(admin)',
    path: '/admin/users',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'Admin blog redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(admin)',
    path: '/admin/blog',
    requiresAuth: true,
    requiresDb: false,
  },
  {
    authenticatedStrategy: 'csr-only',
    description: 'Admin audit redirects to login (unauthenticated)',
    devStrategy: 'redirect',
    expectedStrategy: 'redirect',
    group: '(admin)',
    path: '/admin/audit',
    requiresAuth: true,
    requiresDb: false,
  },
]
